### ISSUE TITLE
UI verbessern

### ISSUE THREAD

**Issue by jannis701** [christian2222/krabbelsack#2]
Verbesserungsvorschläge für die UI:

Eingabe der Namen:
- Nur **ein** Eingabefeld, mit dem ein neuer Name zur Liste hinzugefügt werden kann
- Löschen-Knopf hinter jedem Namen, um diesen von der liste zu entfernen
- keine leeren namen erlauben hinzuzufügen
- keine zwei gleichen namen erlauben

Ausgabe der Ergebnisse:
- Ergebnis nicht direkt anzeigen. Jeder soll ja nur seinen nachfolger sehen können
- Damit eine Person ihren Nachfolger einsehen kann: Namensliste weiterhin anzeigen und bei klick auf den namen den nachfolger anzeigen und einen Button "habe es mir gemerkt". Wenn der Button geklickt wurde,  den namen, dessen nachfolger angezeigt wurde ausblenden/ausgrauen (damit er nicht nochmal angezeigt werden kann und man sieht, dass er schon angezeigt wurde)

**Comment by christian2222** [comment]
ok, verstanden. Dauert aber etwas...
