### ISSUE TITLE
Zuordnung nicht nur im kreis

### ISSUE THREAD

**Issue by jannis701** [christian2222/krabbelsack#3]
Es soll (optional) möglich sein, dass auch mehrere geschlossene Kreise entstehen können.
Also bei vier Namen A, B, C, D sollte auch A->B, B->A, C->D, D->C möglich sein, wenn man die option "gegenseitiges beschenken erlauben" aktiviert hat.

**Comment by christian2222** [comment]
ok, das kann aber etwas Zeit in Anspruch nehmen, da man dazu Permutationen implementieren muss...
